### PR TITLE
Feat/update k8s files

### PR DESCRIPTION
**Pull request by AU2A**
1. Add frontend and oauth to deploy.yaml and service.yaml.
2. Update the backend image in deploy.yaml.
3. Direct HTTP traffic to docentre-frontend-clusterip in ingress.yaml

### CODE REVIEW

**Review by lohsuan — COMMENTED** [review]
I also run it on my GCP using this version. It looks great!
However, the backend will crush (cannot connect db) if I apply them all at the same time in the first time. 
image
image

Maybe changing the order of database to the first place will decrease the problem. Thanks!
(The resources will be created in the order they appear in the file.)

**Comment by AU2A** [comment]
Interesting, I didn't notice this when I executed it.
I only checked if the web functionality was working properly.
I have already updated the order in deploy.yaml.

**Comment by lohsuan** [comment]
> Interesting, I didn't notice this when I executed it. I only checked if the web functionality was working properly. I have already updated the order in deploy.yaml.

Thanks!

**Review by lohsuan — APPROVED** [review]
LGTM!

**Pull request merged**
